version: '2'

services:
  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "dinner_tracker:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/dinner_tracker'
    ports:
      - '8000:8000'